### ISSUE TITLE
filenotfounderror when installing Fallout Shelter

### ISSUE THREAD

**Issue by ghost** [shashlik/shashlik-build#18] opened 2016-03-11 12:17 UTC
Hi,

It's my first attempt to use Shacklik. 

OS : Elementary Freya (Ubuntu 14.04)
Slacklib version : 0.9.3. => deb

Terminal : 
`/opt/shashlik/bin/shashlik-install com.bethsoft.falloutshelter.apk 
Successfully installed Fallout Shelter
Traceback (most recent call last):
  File "/opt/shashlik/bin/shashlik-install", line 109, in <module>
    message ("Successfully installed %s" % app_name)
  File "/opt/shashlik/bin/shashlik-install", line 22, in message
    "--msgbox", msg])
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(_popenargs, *_kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in **init**
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)

FileNotFoundError: [Errno 2] No such file or directory: 'kdialog'
`
Is it a KDE dependancy ? 

Thanks,

**Comment by licaon-kter** [comment] 2016-03-11 13:51
/duplicate of https://github.com/shashlik/shashlik-build/issues/3

**Closed as completed** 2016-04-04 13:14 UTC
